# Site settings
title: Andrea Verlicchi - Blog
subtitle: Making the web faster and delightful
email: andrea.verlicchi@gmail.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  I'm a web development geek specialised in web performance optimisation.
  I write this blog and sometimes I speak at conferences about the web.  
  I'm currently working at Netcentric, a Cognizant digital business.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.andreaverlicchi.eu" # the base hostname & protocol for your site
twitter_username: verlok
github_username:  verlok
markdown: kramdown
include: [.htaccess]
paginate: 20
google_analytics: UA-26756203-1
sass: 
  style: compressed
disqus:
  shortname: andreaverlicchi-blog
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      permalink: /:title/
plugins: [jekyll-paginate]
